# Author: Yurii Pyvovarov <yuriy.pyvovarov@gmail.com>
# Initial setup Raspberry PI
---
- hosts: pi
  remote_user: pi

  tasks:
    - name: Setup locale
      become: yes
      become_method: sudo
      blockinfile:
        dest: /etc/environment
        create: yes
        block: |
          LC_ALL=en_US.UTF-8
          LANG=en_US.UTF-8

    - name: Update all packages to the latest version
      become: yes
      become_method: sudo
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install basic packages
      become: yes
      become_method: sudo
      apt:
        name: '{{item}}'
        state: latest
      with_items:
        - emacs
        - tmux
        - htop
        - iftop
        - iotop

    - name: Set bash setting
      lineinfile:
        path: ~/.bashrc
        line: "export EDITOR='emacs'"
