# Author: Yurii Pyvovarov <yuriy.pyvovarov@gmail.com>
# Turn Raspberry PI to Apple Time Capsule
---
- hosts: pi
  remote_user: pi
  become: yes
  become_method: sudo

  tasks:
    - name: Install netatalk
      become: yes
      become_method: sudo
      apt:
        name: '{{item}}'
        state: latest
      with_items:
        - netatalk

    - name: Enable netatalk service
      systemd:
        name: netatalk.service
        state: started
        enabled: True

    - name: Create directory for backups
      file:
        path: /mnt/storage/TimeMachine
        state: directory
        owner: pi
        group: pi

    - name: Set backup directory
      lineinfile:
        path: /etc/netatalk/AppleVolumes.default
        line: "/mnt/storage/TimeMachine \"Time Machine\" options:tm"
      notify:
        - Restarte netatalk

  handlers:
    - name: Restarte netatalk
      systemd:
        name: netatalk.service
        state: restarted
